# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96776d976be5f6a2c463f25532abb8dfe467eacbf7cde5671e4d9888debf21ff4e080e506d71ff61539bdf4a756118084045d08417ee16a5fcdc4b62a0c7b7e5

test:
  secret_key_base: 9ef0c6e0ff20b1da18ea1d620489387eedd832cf9fd34fd09d59353d58414fdef6e51eb2d7445817185310c0c6ca3531e4fec646092733887c73958eb53e20de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
